from enum import Enum


class StatusPDI(Enum):
    RASCUNHO = "RASCUNHO"
    ATIVO = "ATIVO"
    CONCLUIDO = "CONCLUIDO"
    CANCELADO = "CANCELADO"


class OrigemPDI(Enum):
    AVALIACAO = "AVALIACAO"
    FEEDBACK = "FEEDBACK"
    META = "META"
    INDICACAO_LIDER = "INDICACAO_LIDER"
    AGENTE_IA = "AGENTE_IA"
    MANUAL = "MANUAL"


class TipoAcaoPDI(Enum):
    TREINAMENTO = "TREINAMENTO"
    MENTORIA = "MENTORIA"
    LEITURA = "LEITURA"
    PRATICA_SUPERVISIONADA = "PRATICA_SUPERVISIONADA"
    PARTICIPACAO_PROJETO = "PARTICIPACAO_PROJETO"
    ACOMPANHAMENTO_LIDER = "ACOMPANHAMENTO_LIDER"
    OUTRO = "OUTRO"


class StatusAcaoPDI(Enum):
    PENDENTE = "PENDENTE"
    EM_ANDAMENTO = "EM_ANDAMENTO"
    CONCLUIDA = "CONCLUIDA"
    CANCELADA = "CANCELADA"
