from enum import Enum


class TipoAvaliacao(Enum):
    AUTOAVALIACAO = "AUTOAVALIACAO"
    AVALIACAO_LIDER = "AVALIACAO_LIDER"
    AVALIACAO_TECNICA = "AVALIACAO_TECNICA"
    AVALIACAO_360 = "AVALIACAO_360"
