"""create_reconhecimentos_table

Revision ID: ca4176697e5a
Revises: 11b78d4a7a1f
Create Date: 2026-05-31 18:43:30.610746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ca4176697e5a'
down_revision: Union[str, None] = '11b78d4a7a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconhecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('evidencia', sa.Text(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('data_reconhecimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconhecimentos')
    # ### end Alembic commands ###
