from enum import Enum


class ClassificacaoTalento(Enum):
    ESPECIALISTA_TECNICO = "ESPECIALISTA_TECNICO"
    POTENCIAL_LIDER = "POTENCIAL_LIDER"
    ALTA_PERFORMANCE = "ALTA_PERFORMANCE"
    TALENTO_EM_DESENVOLVIMENTO = "TALENTO_EM_DESENVOLVIMENTO"
    NECESSITA_DESENVOLVIMENTO = "NECESSITA_DESENVOLVIMENTO"
