from enum import Enum


class TipoReconhecimento(Enum):
    DESTAQUE = "DESTAQUE"
    META_ATINGIDA = "META_ATINGIDA"
    EVOLUCAO_TECNICA = "EVOLUCAO_TECNICA"
    COMPORTAMENTO_POSITIVO = "COMPORTAMENTO_POSITIVO"
    CONCLUSAO_TREINAMENTO = "CONCLUSAO_TREINAMENTO"
    CONCLUSAO_PDI = "CONCLUSAO_PDI"
    REDUCAO_RETRABALHO = "REDUCAO_RETRABALHO"
    APOIO_EQUIPE = "APOIO_EQUIPE"
    POTENCIAL_LIDERANCA = "POTENCIAL_LIDERANCA"
    OUTRO = "OUTRO"
